module.exports = {
  //load all flgas, bitmap text, buttons
  preload: function () {
    this.bg = this.game.add.bitmapText(this.world.centerX, this.game.getScaledHeight(400), 'myfont', "Round the World", this.game.getScaledHeight(150));
    this.bg.anchor.setTo(0.5);

    this.globe = this.game.add.sprite(this.world.centerX, this.game.getScaledHeight(700), 'globe');
    this.globe.height = this.game.getScaledHeight(this.globe.height)
    this.globe.width = this.game.getScaledWidth(this.globe.width);
    this.globe.anchor.setTo(0.5);

    this.loadBar = this.game.add.sprite(this.world.centerX, this.game.getScaledHeight(950), 'loadingBar');
    this.loadBar.anchor.setTo(0.5);
    this.load.setPreloadSprite(this.loadBar);
    this.loadBar.height = this.game.getScaledHeight(this.loadBar.height)
    this.loadBar.width = this.game.getScaledWidth(this.loadBar.width);

    this.game.load.image('AF', 'assets/round-the-world/flags/AF.png');
    this.game.load.image('AX', 'assets/round-the-world/flags/AX.png');
    this.game.load.image('AL', 'assets/round-the-world/flags/AL.png');
    this.game.load.image('DZ', 'assets/round-the-world/flags/DZ.png');
    this.game.load.image('AS', 'assets/round-the-world/flags/AS.png');
    this.game.load.image('AD', 'assets/round-the-world/flags/AD.png');
    this.game.load.image('AO', 'assets/round-the-world/flags/AO.png');
    this.game.load.image('AI', 'assets/round-the-world/flags/AI.png');
    this.game.load.image('AQ', 'assets/round-the-world/flags/AQ.png');
    this.game.load.image('AG', 'assets/round-the-world/flags/AG.png');
    this.game.load.image('AR', 'assets/round-the-world/flags/AR.png');
    this.game.load.image('AM', 'assets/round-the-world/flags/AM.png');
    this.game.load.image('AW', 'assets/round-the-world/flags/AW.png');
    this.game.load.image('AU', 'assets/round-the-world/flags/AU.png');
    this.game.load.image('AT', 'assets/round-the-world/flags/AT.png');
    this.game.load.image('AZ', 'assets/round-the-world/flags/AZ.png');
    this.game.load.image('BS', 'assets/round-the-world/flags/BS.png');
    this.game.load.image('BH', 'assets/round-the-world/flags/BH.png');
    this.game.load.image('BD', 'assets/round-the-world/flags/BD.png');
    this.game.load.image('BB', 'assets/round-the-world/flags/BB.png');
    this.game.load.image('BY', 'assets/round-the-world/flags/BY.png');
    this.game.load.image('BE', 'assets/round-the-world/flags/BE.png');
    this.game.load.image('BZ', 'assets/round-the-world/flags/BZ.png');
    this.game.load.image('BJ', 'assets/round-the-world/flags/BJ.png');
    this.game.load.image('BM', 'assets/round-the-world/flags/BM.png');
    this.game.load.image('BT', 'assets/round-the-world/flags/BT.png');
    this.game.load.image('BO', 'assets/round-the-world/flags/BO.png');
    this.game.load.image('BQ', 'assets/round-the-world/flags/BQ.png');
    this.game.load.image('BA', 'assets/round-the-world/flags/BA.png');
    this.game.load.image('BW', 'assets/round-the-world/flags/BW.png');
    this.game.load.image('BV', 'assets/round-the-world/flags/BV.png');
    this.game.load.image('BR', 'assets/round-the-world/flags/BR.png');
    this.game.load.image('IO', 'assets/round-the-world/flags/IO.png');
    this.game.load.image('BN', 'assets/round-the-world/flags/BN.png');
    this.game.load.image('BG', 'assets/round-the-world/flags/BG.png');
    this.game.load.image('BF', 'assets/round-the-world/flags/BF.png');
    this.game.load.image('BI', 'assets/round-the-world/flags/BI.png');
    this.game.load.image('KH', 'assets/round-the-world/flags/KH.png');
    this.game.load.image('CM', 'assets/round-the-world/flags/CM.png');
    this.game.load.image('CA', 'assets/round-the-world/flags/CA.png');
    this.game.load.image('CV', 'assets/round-the-world/flags/CV.png');
    this.game.load.image('KY', 'assets/round-the-world/flags/KY.png');
    this.game.load.image('CF', 'assets/round-the-world/flags/CF.png');
    this.game.load.image('TD', 'assets/round-the-world/flags/TD.png');
    this.game.load.image('CL', 'assets/round-the-world/flags/CL.png');
    this.game.load.image('CN', 'assets/round-the-world/flags/CN.png');
    this.game.load.image('CX', 'assets/round-the-world/flags/CX.png');
    this.game.load.image('CC', 'assets/round-the-world/flags/CC.png');
    this.game.load.image('CO', 'assets/round-the-world/flags/CO.png');
    this.game.load.image('KM', 'assets/round-the-world/flags/KM.png');
    this.game.load.image('CG', 'assets/round-the-world/flags/CG.png');
    this.game.load.image('CD', 'assets/round-the-world/flags/CD.png');
    this.game.load.image('CK', 'assets/round-the-world/flags/CK.png');
    this.game.load.image('CR', 'assets/round-the-world/flags/CR.png');
    this.game.load.image('CI', 'assets/round-the-world/flags/CI.png');
    this.game.load.image('HR', 'assets/round-the-world/flags/HR.png');
    this.game.load.image('CU', 'assets/round-the-world/flags/CU.png');
    this.game.load.image('CW', 'assets/round-the-world/flags/CW.png');
    this.game.load.image('CY', 'assets/round-the-world/flags/CY.png');
    this.game.load.image('CZ', 'assets/round-the-world/flags/CZ.png');
    this.game.load.image('DK', 'assets/round-the-world/flags/DK.png');
    this.game.load.image('DJ', 'assets/round-the-world/flags/DJ.png');
    this.game.load.image('DM', 'assets/round-the-world/flags/DM.png');
    this.game.load.image('DO', 'assets/round-the-world/flags/DO.png');
    this.game.load.image('EC', 'assets/round-the-world/flags/EC.png');
    this.game.load.image('EG', 'assets/round-the-world/flags/EG.png');
    this.game.load.image('SV', 'assets/round-the-world/flags/SV.png');
    this.game.load.image('GQ', 'assets/round-the-world/flags/GQ.png');
    this.game.load.image('ER', 'assets/round-the-world/flags/ER.png');
    this.game.load.image('EE', 'assets/round-the-world/flags/EE.png');
    this.game.load.image('ET', 'assets/round-the-world/flags/ET.png');
    this.game.load.image('FK', 'assets/round-the-world/flags/FK.png');
    this.game.load.image('FO', 'assets/round-the-world/flags/FO.png');
    this.game.load.image('FJ', 'assets/round-the-world/flags/FJ.png');
    this.game.load.image('FI', 'assets/round-the-world/flags/FI.png');
    this.game.load.image('FR', 'assets/round-the-world/flags/FR.png');
    this.game.load.image('GF', 'assets/round-the-world/flags/GF.png');
    this.game.load.image('PF', 'assets/round-the-world/flags/PF.png');
    this.game.load.image('TF', 'assets/round-the-world/flags/TF.png');
    this.game.load.image('GA', 'assets/round-the-world/flags/GA.png');
    this.game.load.image('GM', 'assets/round-the-world/flags/GM.png');
    this.game.load.image('GE', 'assets/round-the-world/flags/GE.png');
    this.game.load.image('DE', 'assets/round-the-world/flags/DE.png');
    this.game.load.image('GH', 'assets/round-the-world/flags/GH.png');
    this.game.load.image('GI', 'assets/round-the-world/flags/GI.png');
    this.game.load.image('GR', 'assets/round-the-world/flags/GR.png');
    this.game.load.image('GL', 'assets/round-the-world/flags/GL.png');
    this.game.load.image('GD', 'assets/round-the-world/flags/GD.png');
    this.game.load.image('GP', 'assets/round-the-world/flags/GP.png');
    this.game.load.image('GU', 'assets/round-the-world/flags/GU.png');
    this.game.load.image('GT', 'assets/round-the-world/flags/GT.png');
    this.game.load.image('GG', 'assets/round-the-world/flags/GG.png');
    this.game.load.image('GN', 'assets/round-the-world/flags/GN.png');
    this.game.load.image('GW', 'assets/round-the-world/flags/GW.png');
    this.game.load.image('GY', 'assets/round-the-world/flags/GY.png');
    this.game.load.image('HT', 'assets/round-the-world/flags/HT.png');
    this.game.load.image('HM', 'assets/round-the-world/flags/HM.png');
    this.game.load.image('VA', 'assets/round-the-world/flags/VA.png');
    this.game.load.image('HN', 'assets/round-the-world/flags/HN.png');
    this.game.load.image('HK', 'assets/round-the-world/flags/HK.png');
    this.game.load.image('HU', 'assets/round-the-world/flags/HU.png');
    this.game.load.image('IS', 'assets/round-the-world/flags/IS.png');
    this.game.load.image('IN', 'assets/round-the-world/flags/IN.png');
    this.game.load.image('ID', 'assets/round-the-world/flags/ID.png');
    this.game.load.image('IR', 'assets/round-the-world/flags/IR.png');
    this.game.load.image('IQ', 'assets/round-the-world/flags/IQ.png');
    this.game.load.image('IE', 'assets/round-the-world/flags/IE.png');
    this.game.load.image('IM', 'assets/round-the-world/flags/IM.png');
    this.game.load.image('IL', 'assets/round-the-world/flags/IL.png');
    this.game.load.image('IT', 'assets/round-the-world/flags/IT.png');
    this.game.load.image('JM', 'assets/round-the-world/flags/JM.png');
    this.game.load.image('JP', 'assets/round-the-world/flags/JP.png');
    this.game.load.image('JE', 'assets/round-the-world/flags/JE.png');
    this.game.load.image('JO', 'assets/round-the-world/flags/JO.png');
    this.game.load.image('KZ', 'assets/round-the-world/flags/KZ.png');
    this.game.load.image('KE', 'assets/round-the-world/flags/KE.png');
    this.game.load.image('KI', 'assets/round-the-world/flags/KI.png');
    this.game.load.image('KP', 'assets/round-the-world/flags/KP.png');
    this.game.load.image('KR', 'assets/round-the-world/flags/KR.png');
    this.game.load.image('KW', 'assets/round-the-world/flags/KW.png');
    this.game.load.image('KG', 'assets/round-the-world/flags/KG.png');
    this.game.load.image('LA', 'assets/round-the-world/flags/LA.png');
    this.game.load.image('LV', 'assets/round-the-world/flags/LV.png');
    this.game.load.image('LB', 'assets/round-the-world/flags/LB.png');
    this.game.load.image('LS', 'assets/round-the-world/flags/LS.png');
    this.game.load.image('LR', 'assets/round-the-world/flags/LR.png');
    this.game.load.image('LY', 'assets/round-the-world/flags/LY.png');
    this.game.load.image('LI', 'assets/round-the-world/flags/LI.png');
    this.game.load.image('LT', 'assets/round-the-world/flags/LT.png');
    this.game.load.image('LU', 'assets/round-the-world/flags/LU.png');
    this.game.load.image('MO', 'assets/round-the-world/flags/MO.png');
    this.game.load.image('MK', 'assets/round-the-world/flags/MK.png');
    this.game.load.image('MG', 'assets/round-the-world/flags/MG.png');
    this.game.load.image('MW', 'assets/round-the-world/flags/MW.png');
    this.game.load.image('MY', 'assets/round-the-world/flags/MY.png');
    this.game.load.image('MV', 'assets/round-the-world/flags/MV.png');
    this.game.load.image('ML', 'assets/round-the-world/flags/ML.png');
    this.game.load.image('MT', 'assets/round-the-world/flags/MT.png');
    this.game.load.image('MH', 'assets/round-the-world/flags/MH.png');
    this.game.load.image('MQ', 'assets/round-the-world/flags/MQ.png');
    this.game.load.image('MR', 'assets/round-the-world/flags/MR.png');
    this.game.load.image('MU', 'assets/round-the-world/flags/MU.png');
    this.game.load.image('YT', 'assets/round-the-world/flags/YT.png');
    this.game.load.image('MX', 'assets/round-the-world/flags/MX.png');
    this.game.load.image('FM', 'assets/round-the-world/flags/FM.png');
    this.game.load.image('MD', 'assets/round-the-world/flags/MD.png');
    this.game.load.image('MC', 'assets/round-the-world/flags/MC.png');
    this.game.load.image('MN', 'assets/round-the-world/flags/MN.png');
    this.game.load.image('ME', 'assets/round-the-world/flags/ME.png');
    this.game.load.image('MS', 'assets/round-the-world/flags/MS.png');
    this.game.load.image('MA', 'assets/round-the-world/flags/MA.png');
    this.game.load.image('MZ', 'assets/round-the-world/flags/MZ.png');
    this.game.load.image('MM', 'assets/round-the-world/flags/MM.png');
    this.game.load.image('NA', 'assets/round-the-world/flags/NA.png');
    this.game.load.image('NR', 'assets/round-the-world/flags/NR.png');
    this.game.load.image('NP', 'assets/round-the-world/flags/NP.png');
    this.game.load.image('NL', 'assets/round-the-world/flags/NL.png');
    this.game.load.image('NC', 'assets/round-the-world/flags/NC.png');
    this.game.load.image('NZ', 'assets/round-the-world/flags/NZ.png');
    this.game.load.image('NI', 'assets/round-the-world/flags/NI.png');
    this.game.load.image('NE', 'assets/round-the-world/flags/NE.png');
    this.game.load.image('NG', 'assets/round-the-world/flags/NG.png');
    this.game.load.image('NU', 'assets/round-the-world/flags/NU.png');
    this.game.load.image('NF', 'assets/round-the-world/flags/NF.png');
    this.game.load.image('MP', 'assets/round-the-world/flags/MP.png');
    this.game.load.image('NO', 'assets/round-the-world/flags/NO.png');
    this.game.load.image('OM', 'assets/round-the-world/flags/OM.png');
    this.game.load.image('PK', 'assets/round-the-world/flags/PK.png');
    this.game.load.image('PW', 'assets/round-the-world/flags/PW.png');
    this.game.load.image('PS', 'assets/round-the-world/flags/PS.png');
    this.game.load.image('PA', 'assets/round-the-world/flags/PA.png');
    this.game.load.image('PG', 'assets/round-the-world/flags/PG.png');
    this.game.load.image('PY', 'assets/round-the-world/flags/PY.png');
    this.game.load.image('PE', 'assets/round-the-world/flags/PE.png');
    this.game.load.image('PH', 'assets/round-the-world/flags/PH.png');
    this.game.load.image('PN', 'assets/round-the-world/flags/PN.png');
    this.game.load.image('PL', 'assets/round-the-world/flags/PL.png');
    this.game.load.image('PT', 'assets/round-the-world/flags/PT.png');
    this.game.load.image('PR', 'assets/round-the-world/flags/PR.png');
    this.game.load.image('QA', 'assets/round-the-world/flags/QA.png');
    this.game.load.image('RE', 'assets/round-the-world/flags/RE.png');
    this.game.load.image('RO', 'assets/round-the-world/flags/RO.png');
    this.game.load.image('RU', 'assets/round-the-world/flags/RU.png');
    this.game.load.image('RW', 'assets/round-the-world/flags/RW.png');
    this.game.load.image('BL', 'assets/round-the-world/flags/BL.png');
    this.game.load.image('SH', 'assets/round-the-world/flags/SH.png');
    this.game.load.image('KN', 'assets/round-the-world/flags/KN.png');
    this.game.load.image('LC', 'assets/round-the-world/flags/LC.png');
    this.game.load.image('MF', 'assets/round-the-world/flags/MF.png');
    this.game.load.image('PM', 'assets/round-the-world/flags/PM.png');
    this.game.load.image('VC', 'assets/round-the-world/flags/VC.png');
    this.game.load.image('WS', 'assets/round-the-world/flags/WS.png');
    this.game.load.image('SM', 'assets/round-the-world/flags/SM.png');
    this.game.load.image('ST', 'assets/round-the-world/flags/ST.png');
    this.game.load.image('SA', 'assets/round-the-world/flags/SA.png');
    this.game.load.image('SN', 'assets/round-the-world/flags/SN.png');
    this.game.load.image('RS', 'assets/round-the-world/flags/RS.png');
    this.game.load.image('SC', 'assets/round-the-world/flags/SC.png');
    this.game.load.image('SL', 'assets/round-the-world/flags/SL.png');
    this.game.load.image('SG', 'assets/round-the-world/flags/SG.png');
    this.game.load.image('SX', 'assets/round-the-world/flags/SX.png');
    this.game.load.image('SK', 'assets/round-the-world/flags/SK.png');
    this.game.load.image('SI', 'assets/round-the-world/flags/SI.png');
    this.game.load.image('SB', 'assets/round-the-world/flags/SB.png');
    this.game.load.image('SO', 'assets/round-the-world/flags/SO.png');
    this.game.load.image('ZA', 'assets/round-the-world/flags/ZA.png');
    this.game.load.image('GS', 'assets/round-the-world/flags/GS.png');
    this.game.load.image('SS', 'assets/round-the-world/flags/SS.png');
    this.game.load.image('ES', 'assets/round-the-world/flags/ES.png');
    this.game.load.image('LK', 'assets/round-the-world/flags/LK.png');
    this.game.load.image('SD', 'assets/round-the-world/flags/SD.png');
    this.game.load.image('SR', 'assets/round-the-world/flags/SR.png');
    this.game.load.image('SJ', 'assets/round-the-world/flags/SJ.png');
    this.game.load.image('SZ', 'assets/round-the-world/flags/SZ.png');
    this.game.load.image('SE', 'assets/round-the-world/flags/SE.png');
    this.game.load.image('CH', 'assets/round-the-world/flags/CH.png');
    this.game.load.image('SY', 'assets/round-the-world/flags/SY.png');
    this.game.load.image('TW', 'assets/round-the-world/flags/TW.png');
    this.game.load.image('TJ', 'assets/round-the-world/flags/TJ.png');
    this.game.load.image('TZ', 'assets/round-the-world/flags/TZ.png');
    this.game.load.image('TH', 'assets/round-the-world/flags/TH.png');
    this.game.load.image('TL', 'assets/round-the-world/flags/TL.png');
    this.game.load.image('TG', 'assets/round-the-world/flags/TG.png');
    this.game.load.image('TK', 'assets/round-the-world/flags/TK.png');
    this.game.load.image('TO', 'assets/round-the-world/flags/TO.png');
    this.game.load.image('TT', 'assets/round-the-world/flags/TT.png');
    this.game.load.image('TN', 'assets/round-the-world/flags/TN.png');
    this.game.load.image('TR', 'assets/round-the-world/flags/TR.png');
    this.game.load.image('TM', 'assets/round-the-world/flags/TM.png');
    this.game.load.image('TC', 'assets/round-the-world/flags/TC.png');
    this.game.load.image('TV', 'assets/round-the-world/flags/TV.png');
    this.game.load.image('UG', 'assets/round-the-world/flags/UG.png');
    this.game.load.image('UA', 'assets/round-the-world/flags/UA.png');
    this.game.load.image('AE', 'assets/round-the-world/flags/AE.png');
    this.game.load.image('GB', 'assets/round-the-world/flags/GB.png');
    this.game.load.image('US', 'assets/round-the-world/flags/US.png');
    this.game.load.image('UM', 'assets/round-the-world/flags/UM.png');
    this.game.load.image('UY', 'assets/round-the-world/flags/UY.png');
    this.game.load.image('UZ', 'assets/round-the-world/flags/UZ.png');
    this.game.load.image('VU', 'assets/round-the-world/flags/VU.png');
    this.game.load.image('VE', 'assets/round-the-world/flags/VE.png');
    this.game.load.image('VN', 'assets/round-the-world/flags/VN.png');
    this.game.load.image('VG', 'assets/round-the-world/flags/VG.png');
    this.game.load.image('VI', 'assets/round-the-world/flags/VI.png');
    this.game.load.image('WF', 'assets/round-the-world/flags/WF.png');
    this.game.load.image('EH', 'assets/round-the-world/flags/EH.png');
    this.game.load.image('YE', 'assets/round-the-world/flags/YE.png');
    this.game.load.image('ZM', 'assets/round-the-world/flags/ZM.png');
    this.game.load.image('ZW', 'assets/round-the-world/flags/ZW.png');

    this.game.load.image('leftArrow', 'assets/round-the-world/images/leftArrow.png');
    this.game.load.image('rightArrow', 'assets/round-the-world/images/rightArrow.png');
    this.game.load.spritesheet('option', 'assets/round-the-world/images/options.png', 404, 304, 3);
    this.game.load.image('btFlag', 'assets/round-the-world/images/bt2.png');
    this.game.load.image('btBack', 'assets/round-the-world/images/back.png');
    this.game.load.image('btHome', 'assets/round-the-world/images/options.png');
    this.game.load.bitmapFont('myguifont', 'assets/round-the-world/fonts/guifont.png', 'assets/round-the-world/fonts/guifont.fnt');
    this.game.load.spritesheet('lives', 'assets/round-the-world/images/lives.png', 324, 68, 5);
    this.game.load.text('infoAF', 'assets/round-the-world/data/countries.json ');

    this.game.load.audio('correct', 'assets/round-the-world/audio/correct.ogg');
    this.game.load.audio('wrong', 'assets/round-the-world/audio/wrong.ogg');
    this.game.load.audio('next', 'assets/round-the-world/audio/next.ogg');
    this.game.load.audio('back', 'assets/round-the-world/audio/back.ogg');
    this.game.load.audio('correct2', 'assets/round-the-world/audio/correct2.ogg');
    this.game.load.audio('click', 'assets/round-the-world/audio/click.ogg');
    this.game.load.audio('streak', 'assets/round-the-world/audio/streak.ogg');
    this.game.load.audio('won', 'assets/round-the-world/audio/gamewon.ogg');
    this.game.load.audio('over', 'assets/round-the-world/audio/gameover.ogg');

  },

  create: function () {
    for (var i = 0; i < 5; i++) {
      for (var j = 0; j < 5; j++) {
        console.log('' + i + '' + j);
        console.log(localStorage.getItem('' + i + '' + j));
        if (localStorage.getItem('' + i + '' + j) == null) { }
        else {
          this.game.global.highscore[i][j] = localStorage.getItem('' + i + '' + j);
        }
      }
      this.state.start('menuState');


    }
  }
}
